### ISSUE TITLE
Update code signing settings

### ISSUE THREAD

**Issue by ianbytchek** [PureLayout/PureLayout#105]
Just a friendly suggestion based on this [comment](https://github.com/Carthage/Carthage/issues/399#issuecomment-86089516) of this [issue](https://github.com/Carthage/Carthage/issues/399). Carthage folks seem to agree with this:

> * iOS Framework (CODE_SIGN_IDENTITY = `iPhone Developer`)
> * iOS Framework Tests (CODE_SIGN_IDENTITY = `iPhone Developer`)
> * OSX Framework (CODE_SIGN_IDENTITY = `Don't Code Sign`)
> * OSX Framework Tests (CODE_SIGN_IDENTITY = `Don't Code Sign`)

Asking this because with PureLayout as it is I get a `Skipping build for "macosx" SDK because the necessary signing identity "-" is not installed` warning. Changing code signing identity from `"-"` to something else solves this, but every time I update dependencies this gets reset to `"-"`. Or am I'm missing a point here?

**Comment by schemers** [comment]
+1 on this. Hadn't updated Carthage in a while,and this issue cropped up. Seems OK on Carthage 0.8, but later Carthage versions get this error when building PureLayout. 

Suggested change allows it to get built.

I still wonder if this is something Carthage should address, since codesign(1) man page has this to say about "-":

> If identity is the single letter "-" (dash), ad-hoc signing is performed.  Ad-hoc signing does not use
>     an identity at all, and identifies exactly one instance of code. Significant restrictions apply to the
>     use of ad-hoc signed code; consult documentation before using this.

I think Carthage's intentions are to make sure all coding signing identities specified in the project are available as a precondition, and it isn't handling "-" as special.

**Comment by mickeyreiss** [comment]
I'd be happy to make a change related to this issue as long as the library continues to build satisfactorily for all integration styles.

**Comment by ianbytchek** [comment]
@mickeyreiss to my best knowledge it should be fine. The thing with `-` signature appears to be a part of small inconsistency.

![2016-05-10 10 08 26](https://cloud.githubusercontent.com/assets/1086845/15136961/4d25b27c-1697-11e6-9f42-c3761ce8137d.gif)

Default project code signing is already setup properly to make Carthage happy. I suggest to clear all target code signing preferences to use default project configuration, at the moment only `PureLayout_Mac` and `Example-Mac` targets use customised signing.

**Comment by bitserf** [comment]
FYI, I had this issue (with an oldish version of Carthage) but updating Carthage to 0.16.2 resolved it, so they must have made a change to support the "-" identity. 

Not sure this is a problem for PureLayout to fix.

**Comment by ianbytchek** [comment]
@bitserf who else would it be to fix for? Yes, works for me too with latest Carthage. Great. I guess this is a very small change. Throwing a PR for the sake of everyone's time.

**Comment by ianbytchek** [comment]
@mickeyreiss I guess this is a very small change. Throwing a PR for the sake of everyone's time.
