### ISSUE TITLE
No known class method for selector 'autoCreateConstraintsWithoutInstalling:

### ISSUE THREAD

**Issue by engmsaleh** [PureLayout/PureLayout#114]
I get the following error when I try to use `autoCreateConstraintsWithoutInstalling` method , although I have `#import "PureLayout.h"` already imported , I'm using the latest `PureLayout` from CocoaPods
I'm using exactly `PureLayout (3.0.1)` .
In another project using `PureLayout (2.0.6)` it works just fine.

**Comment by joshbax** [comment]
This started happening in the objective-c portion of my app after upgrading. The swift code now uses **NSLayoutConstraint**.autoCreateConstraintsWithoutInstalling(), but I'm getting method-not-found errors in objective-c. 
Any updates on this?

**Comment by engmsaleh** [comment]
@joshbax  How to solve it if project is only `Objective-c`?

**Comment by joshbax** [comment]
@engmsaleh 
[NSLayoutConstraint autoCreateConstraintsWithoutInstalling:...] works in objective-c with the latest version of PureLayout. Make sure to clear the build folder. If you installed PureLayout with carthage you'll have to use the @import statement in Objective-c. If you're using Cocoa Pods it should work as normal.
