### ISSUE TITLE
Future of Autolayout

### ISSUE THREAD

**Issue by Fosile** [PureLayout/PureLayout#115]
This is not a real issue, more a question. I will start a new iOS Project soon, and i don´t really like the Interface Builder, especially when you have a more complex Layout.
So i always write my Constraints in Code, but as we all know it can sometimes be really annoying with the Apple standard Code. So i would prefer something like PureLayout or SnapKit

My Problem is, what happens when Apple decide to release something similar to PureLayout or SnapKit, which would make it a lot of easier. I really don´t want to rewrite my whole Project in a few Month only because of some new Autolayout Stuff which is maybe not compatible with this Third Library Code.
What do you think about this?

**Comment by mickeyreiss** [comment]
PureLayout is implemented as a thin wrapper around AutoLayout. The main design goal is to help you write more maintainable layout code fluidly and efficiently while working in the grain with UIKit.

If Apple breaks auto layout, PureLayout code will break in almost exactly the same way as normal auto layout code (although I can't speak to the visual format language or interface builder.

In other news, I'd recommend taking a look at @smileyborg's [Twitter profile](https://twitter.com/smileyborg). He's the original author of this library and is now working on something....different :)
