### ISSUE TITLE
UITableViewCell not getting proper Height...

### ISSUE THREAD

**Issue by googler2013** [PureLayout/PureLayout#120]
Hello, 

I am facing one issue to do in UITableViewCell dynamic height, below is the screenshot of demo.

![screen shot 2016-01-11 at 12 41 00 pm](https://cloud.githubusercontent.com/assets/29055/12228407/1cae8d92-b861-11e5-95ae-894484e3982a.png)

Issue:
- In the last row Reason is not work as a multiline, here is the code of AutoLayout code 

               [NSLayoutConstraint autoSetPriority:UILayoutPriorityRequired forConstraints:^{
            [self.lblTitleReason autoSetContentCompressionResistancePriorityForAxis:ALAxisVertical];
        }];
        [self.lblTitleReason autoPinEdgeToSuperviewEdge:ALEdgeLeading withInset:kLabelHorizontalInsets];
        [self.lblTitleReason autoPinEdge:ALEdgeTop toEdge:ALEdgeBottom ofView:self.lblStatus withOffset:kLabelVerticalInsets relation:NSLayoutRelationEqual];
        [self.lblTitleReason autoSetDimension:ALDimensionWidth toSize:55];
        
        
        [self.lblReason autoPinEdge:ALEdgeLeading toEdge:ALEdgeTrailing ofView:self.lblTitleReason withOffset:kSpaceBetweenImageAndText relation:NSLayoutRelationEqual];
        [self.lblReason autoPinEdge:ALEdgeTop toEdge:ALEdgeBottom ofView:self.lblStatus withOffset:kLabelVerticalInsets relation:NSLayoutRelationGreaterThanOrEqual];

        [NSLayoutConstraint autoSetPriority:UILayoutPriorityRequired forConstraints:^{
            [self.lblReason autoSetContentCompressionResistancePriorityForAxis:ALAxisVertical];
        }];
        [self.lblReason autoPinEdgeToSuperviewEdge:ALEdgeTrailing withInset:kLabelVerticalInsets];
        [self.lblReason autoPinEdgeToSuperviewEdge:ALEdgeBottom withInset:kLabelVerticalTopBottomInsets];

**Comment by googler2013** [comment]
Hello, please anyone answer for the same...

**Comment by wmbnm** [comment]
I'm facing this too, then I found out something. While in a tableviewCell, you'd better not use autoPinEdgeToSuperviewEdge: but autoPinEdge: toEdge: ofView: withOffset:

**Comment by Ricardo1980** [comment]
Try to use SparkInspector or Reveal to see the constraints in real time, even modify them. It is very useful for debugging UI.
