### ISSUE TITLE
Crashing with -[PKBSideNavView autoPinEdge:toEdge:ofView:]: unrecognized selector sent to instance

### ISSUE THREAD

**Issue by ehlersd** [PureLayout/PureLayout#121]
Had a weird issue with Xcode and actool crashing.  Tried everything, eventually uninstalled and reinstalled Xcode.  That fixed this problem....BUT....

Suddenly this crashing is occurring, consistently on every use of the autoPinEdge.  No compile errors or warnings.....just this crash at runtime with code that has been working well for weeks.

I've also confirmed with git no code changes at all.

Any ideas?

**Comment by danie11am** [comment]
Have you tried deleting DerivedData directory already by any chance?

**Comment by danie11am** [comment]
Actually.. it's more likely that your view has been deallocated at runtime.

**Comment by ehlersd** [comment]
I'm really at a loss.  I rewound my last git commit (no source code changes) which was basically a pod update and then it worked.....but the git commit includes no changes in PureLayout either.  This is a strange one, but so was having to uninstall/reinstall Xcode....so I'm going to chalk this up to to gremlins.

I'm going to slowly update my pods individually and see if the problem returns.  I'll update this if I find out any additional information, but for now, I'd consider this issue closed.

**Comment by smileyborg** [comment]
This type of crash generally means that your app is not properly linked with the PureLayout static library/framework.

**Comment by danie11am** [comment]
If you want to be extra careful when handling changing of pods and CocoaPods versions etc, delete the `Pods` folder and do `pod install` again when you make a change to `Podfile`. And also remove the `DerivedData` directory.
