### ISSUE TITLE
Pure layout usage with App Extensions and Carthage

### ISSUE THREAD

**Issue by adonaire-sage** [PureLayout/PureLayout#122]
I am using PureLayout with Carthage and I have read that it can be configured with a preprocessor macro to allow app extension usage as explained in this wiki page: https://github.com/PureLayout/PureLayout/wiki/App-Extensions

That works with the cases explained in the Wiki, but using carthage to add PureLayout as a framework, there is no solution. Is there a way to activate this preprocessor macro with Carthage I might have missed?

Maybe it's a Carthage issue where the Cartfile should allow a similar configuration to Cocoapods. Thanks for any input.

**Comment by mickeyreiss** [comment]
In https://github.com/PureLayout/PureLayout/issues/114#issuecomment-173006434, @joshbax comments that this can be achieved by `@import`ing the library in Objective-C.
