### ISSUE TITLE
Auto complete broken

### ISSUE THREAD

**Issue by expkzb** [PureLayout/PureLayout#127]
Something like ALEdgeLeading, ALAxisHorizontal can not be auto completed in Xcode 7.3.
Any one else?

**Comment by hydrated** [comment]
I solve the problem by this 
http://stackoverflow.com/questions/36165865/xcode-7-3-syntax-highlighting-and-code-completion-issues-with-swift
Maybe you could try .

**Comment by mickeyreiss** [comment]
Please reopen if still an issue in Xcode 8.
