### ISSUE TITLE
New cocoapods version for tvos ?

### ISSUE THREAD

**Issue by arsonik** [PureLayout/PureLayout#130]
Hi !

Thank you so much for your amazing work.
But can someone tag/push to cocoapods repo a new version like 3.0.2
So we can use PureLayout as a dependency, in other tvos related pods.
```
- ERROR | [tvOS] unknown: Encountered an unknown error (The platform of the target `App` (tvOS 9.0) is not compatible with `PureLayout (3.0.1)`, which does not support `tvos`.) during validation.
```

Cheers

**Comment by pashaisthebest** [comment]
pod 'PureLayout', :git => 'https://github.com/PureLayout/PureLayout.git'
this should fix your problem

**Comment by arsonik** [comment]
@pashaisthebest Not when its used as a pod dependency from another pod ! (podspec)

**Comment by mickeyreiss** [comment]
Yes, I can cut a release!

**Comment by mickeyreiss** [comment]
Tagged on https://github.com/PureLayout/PureLayout/releases/tag/v3.0.2 and pushed to http://cocoapods.org/pods/PureLayout/.

**Comment by arsonik** [comment]
Thanks !
