### ISSUE TITLE
Distribute views horizontal with left and right spacing different then space between

### ISSUE THREAD

**Issue by donpironet** [PureLayout/PureLayout#132]
I want my views to distribute horizontal so I use this:

`buttons.autoDistributeViewsAlongAxis(.Horizontal, alignedTo: .Horizontal, withFixedSpacing: 8, insetSpacing: true)`

But then I get the same spacing right and left off 8. I want left and right 15 and between the buttons 8.

How can I do this?

**Comment by mickeyreiss** [comment]
I believe this is a duplicate of https://github.com/PureLayout/PureLayout/issues/166. @niknovak describes one potential solution in that issue. Otherwise, it sounds like first-class support for this could be useful.

Closing this to consolidate the discussions.
