### ISSUE TITLE
Documenting convenience init(forAutoLayout: ()) 

### ISSUE THREAD

**Issue by acegreen** [PureLayout/PureLayout#134]
It would be nice if we can document the use of init(forAutoLayout: ()).
I tried to subclass with that custom init but can't seem to get the equivalent super.init working

import UIKit

```
class CustomAdView: UIView {

    init(forAutoLayout: ()) {

        super.init(forAutoLayout: ())
    }

    required init?(coder aDecoder: NSCoder) {
        fatalError("init(coder:) has not been implemented")
    }

}
```

**Comment by acegreen** [comment]
It seems you can't override it, you can just use it?

For example:
adBannerView = CustomAdView(forAutoLayout: ())

**Comment by acegreen** [comment]
I tried the following but my frame is still nil

            customView = CustomView(forAutoLayout: ())
            self.view.addSubview(customView)
            customView.autoPinEdgesToSuperviewEdgesWithInsets(UIEdgeInsetsZero, excludingEdge: .Bottom)

**Comment by sebthiriet** [comment]
Is your post related to the issue I just opened: https://github.com/PureLayout/PureLayout/issues/149
I'm not aware of this init(forAutoLayout: ())... I don't find indeed any documentation for this...

**Comment by pronebird** [comment]
It's just super weird to see that method with Void argument. Is it possible to annotate it to be something else in Swift? Why can't it be UIView.initForAutolayout() or even unavailable at all?
