### ISSUE TITLE
How can I make an extension for this using Swift?

### ISSUE THREAD

**Issue by GoldenJoe** [PureLayout/PureLayout#136]
I recently made the switch to Swift, and I've run into a minor problem with PureLayout. Previously, I had extended it with several convenience functions like the following:

`-(NSArray *)autoPinEdgesToSuperviewEdges:(ALEdge)edges withInsets:(UIEdgeInsets)insets
{
    UIView *superview = self.superview;
    NSAssert(superview, @"View's superview must not be nil.\nView: %@", self);
    NSMutableArray *constraints = [NSMutableArray new];
    if((edges & ALEdgeBottom)   != 0) [constraints addObject:[self autoPinEdge:ALEdgeBottom     toEdge:ALEdgeBottom     ofView:superview withOffset:-insets.bottom]];
    if((edges & ALEdgeLeading)  != 0) [constraints addObject:[self autoPinEdge:ALEdgeLeading    toEdge:ALEdgeLeading    ofView:superview withOffset:insets.left]];
    if((edges & ALEdgeLeft)     != 0) [constraints addObject:[self autoPinEdge:ALEdgeLeft       toEdge:ALEdgeLeft       ofView:superview withOffset:insets.left]];
    if((edges & ALEdgeRight)    != 0) [constraints addObject:[self autoPinEdge:ALEdgeRight      toEdge:ALEdgeRight      ofView:superview withOffset:-insets.right]];
    if((edges & ALEdgeTop)      != 0) [constraints addObject:[self autoPinEdge:ALEdgeTop        toEdge:ALEdgeTop        ofView:superview withOffset:insets.top]];
    if((edges & ALEdgeTrailing) != 0) [constraints addObject:[self autoPinEdge:ALEdgeTrailing   toEdge:ALEdgeTrailing   ofView:superview withOffset:-insets.right]];
    return constraints;
}`

It isn't clear, however, how I can recreate my extensions in Swift.

EDIT: Wow, so much for code formatting. It doesn't really matter what the extensions were, I just want to be able to do them again.

**Comment by stefandeclerck** [comment]
Use an ObjC bridging header. That should help.

**Comment by GoldenJoe** [comment]
Maybe a more modern solution?

**Comment by mickeyreiss** [comment]
PureLayout will likely remain an objective-c framework for the time being. Please submit PRs if you have extensions that you believe will save others time and lines of code.
