### ISSUE TITLE
Dynamic Contentsize of UIScrollView

### ISSUE THREAD

**Issue by wajahatch888** [PureLayout/PureLayout#138]
I have a situation in which i want to add multiple text fields in UIScrollView.  Every thing is working fine except if number of text fields increase the screen size then i am unable to dynamically set Content size of UIScrollView. Can you please tell me how it is possible to dynamically increase content size of UIScrollView?

**Comment by wajahatch888** [comment]
Can anyone please answer

**Comment by LuoLee** [comment]
You could set the UIScrollView contentSize in the `viewDidLayout` by caulate the textField bounds.
