### ISSUE TITLE
-[UIView autoPinEdgesToSuperviewEdgesWithInsets:]: unrecognized selector sent to instance

### ISSUE THREAD

**Issue by Jhonny12345** [PureLayout/PureLayout#140]
Hi, 

I am using [Crosspromoter](https://github.com/mergesort/CrossPromoter) (for showing ads) that uses PureLayout. 

I am using it in an old xcode project (ios 6.0 and xcode 7) that use xib (nib files) instead storyboards. PureLayout code is working fine when I use test it in a new project with storyboards but the same code is not working with xib. 

I selected  "Auto Layout" checkbox in xib property but got same error. Is there anything specific that I need to do when using PureLayout with xib instead storyboards. 

I am getting following issue 

> **\* Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[UIView autoPinEdgesToSuperviewEdgesWithInsets:]: unrecognized selector sent to instance 0x7babb9a0'
> **\* First throw call stack:
> (
>     0   CoreFoundation                      0x03626746 **exceptionPreprocess + 182
>     1   libobjc.A.dylib                     0x032afa97 objc_exception_throw + 44
>     2   CoreFoundation                      0x0362e705 -[NSObject(NSObject) doesNotRecognizeSelector:] + 277
>     3   CoreFoundation                      0x03575287 ___forwarding_** + 1047
>     4   CoreFoundation                      0x03574e4e _CF_forwarding_prep_0 + 14
>     5   IKYG              0x000668bf -[AdvertisementViewController setupConstraints] + 271
>     6   IKYG              0x00066767 -[AdvertisementViewController commonInit] + 6615
>     7   IKYG              0x00064d1e -[AdvertisementViewController initWithFeaturedApp:displayMode:] + 606
>     8   IKYG              0x00069c4f -[datepickerViewController tappedInterstitial:] + 495
>     9   libobjc.A.dylib                     0x032c57cd -[NSObject performSelector:withObject:withObject:] + 84
>     10  UIKit                               0x01e2ca40 -[UIApplication sendAction:to:from:forEvent:] + 99
>     11  UIKit                               0x01e2c9d2 -[UIApplication sendAction:toTarget:fromSender:forEvent:] + 64
>     12  UIKit                               0x01f6d13a -[UIControl sendAction:to:forEvent:] + 69
>     13  UIKit                               0x01f6d557 -[UIControl _sendActionsForEvents:withEvent:] + 598
>     14  UIKit                               0x01f6c7c1 -[UIControl touchesEnded:withEvent:] + 660
>     15  UIKit                               0x01e84caa -[UIWindow _sendTouchesForEvent:] + 874
>     16  UIKit                               0x01e85786 -[UIWindow sendEvent:] + 792
>     17  UIKit                               0x01e43681 -[UIApplication sendEvent:] + 242
>     18  UIKit                               0x01e53ab8 _UIApplicationHandleEventFromQueueEvent + 21484
>     19  UIKit                               0x01e272e7 _UIApplicationHandleEventQueue + 2300
>     20  CoreFoundation                      0x0354806f __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 15
>     21  CoreFoundation                      0x0353db7d __CFRunLoopDoSources0 + 253
>     22  CoreFoundation                      0x0353d0d8 __CFRunLoopRun + 952
>     23  CoreFoundation                      0x0353ca5b CFRunLoopRunSpecific + 443
>     24  CoreFoundation                      0x0353c88b CFRunLoopRunInMode + 123
>     25  GraphicsServices                    0x054732c9 GSEventRunModal + 192
>     26  GraphicsServices                    0x05473106 GSEventRun + 104
>     27  UIKit                               0x01e2b0b6 UIApplicationMain + 1526
>     28  IKYG              0x00063159 main + 89
>     29  libdyld.dylib                       0x03addac9 start + 1
>     30  ???                                 0x00000001 0x0 + 1
> )
> libc++abi.dylib: terminating with uncaught exception of type NSException

Here is the link of the AdvertisementViewController.m file that is showing error. I didn't change anything in this AdvertisementViewController.m file (using it as it is) and it is working fine with storyboards but not with xibs.
[AdvertisementViewController.m](https://github.com/mergesort/CrossPromoter/blob/master/src/AdvertisementViewController.m)

Here is the code where app is crashing when I am selecting an Interstitial Ad.

`if (self.displayMode == DisplayModeInterstitial) {
            [self.interstitialView autoPinEdgesToSuperviewEdgesWithInsets:UIEdgeInsetsZero];
.....
....
}
`
I am also getting the similar error when I select a banner ad. I am getting following issue

> **\* Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[UIView autoSetDimension:toSize:]: unrecognized selector sent to instance 0x7bb58910'
> **\* First throw call stack:
> (
>     0   CoreFoundation                      0x03643746 **exceptionPreprocess + 182
>     1   libobjc.A.dylib                     0x032cca97 objc_exception_throw + 44
>     2   CoreFoundation                      0x0364b705 -[NSObject(NSObject) doesNotRecognizeSelector:] + 277
>     3   CoreFoundation                      0x03592287 ___forwarding_** + 1047
>     4   CoreFoundation                      0x03591e4e _CF_forwarding_prep_0 + 14
>     5   IKYG              0x000842f4 -[AdvertisementViewController setupConstraints] + 2884
>     6   IKYG              0x00083767 -[AdvertisementViewController commonInit] + 6615
>     7   IKYG              0x00081d1e -[AdvertisementViewController initWithFeaturedApp:displayMode:] + 606
>     8   IKYG              0x00086fc3 -[datepickerViewController tappedBanner:] + 643
>     9   libobjc.A.dylib                     0x032e27cd -[NSObject performSelector:withObject:withObject:] + 84
>     10  UIKit                               0x01e49a40 -[UIApplication sendAction:to:from:forEvent:] + 99
>     11  UIKit                               0x01e499d2 -[UIApplication sendAction:toTarget:fromSender:forEvent:] + 64
>     12  UIKit                               0x01f8a13a -[UIControl sendAction:to:forEvent:] + 69
>     13  UIKit                               0x01f8a557 -[UIControl _sendActionsForEvents:withEvent:] + 598
>     14  UIKit                               0x01f897c1 -[UIControl touchesEnded:withEvent:] + 660
>     15  UIKit                               0x01ea1caa -[UIWindow _sendTouchesForEvent:] + 874
>     16  UIKit                               0x01ea2786 -[UIWindow sendEvent:] + 792
>     17  UIKit                               0x01e60681 -[UIApplication sendEvent:] + 242
>     18  UIKit                               0x01e70ab8 _UIApplicationHandleEventFromQueueEvent + 21484
>     19  UIKit                               0x01e442e7 _UIApplicationHandleEventQueue + 2300
>     20  CoreFoundation                      0x0356506f __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 15
>     21  CoreFoundation                      0x0355ab7d __CFRunLoopDoSources0 + 253
>     22  CoreFoundation                      0x0355a0d8 __CFRunLoopRun + 952
>     23  CoreFoundation                      0x03559a5b CFRunLoopRunSpecific + 443
>     24  CoreFoundation                      0x0355988b CFRunLoopRunInMode + 123
>     25  GraphicsServices                    0x054902c9 GSEventRunModal + 192
>     26  GraphicsServices                    0x05490106 GSEventRun + 104
>     27  UIKit                               0x01e480b6 UIApplicationMain + 1526
>     28  IKYG              0x00080159 main + 89
>     29  libdyld.dylib                       0x03afaac9 start + 1
>     30  ???                                 0x00000001 0x0 + 1
> )
> libc++abi.dylib: terminating with uncaught exception of type NSException

Here is the code where app is crashing when I am selecting a banner ad

`else if (self.displayMode == DisplayModeBanner) {
            [self.bannerView autoSetDimension:ALDimensionHeight toSize:AdvertisementViewControllerBannerHeight];
....
....
}
`

Please help.

Thanks.

**Comment by huangboju** [comment]
I get it too

**Comment by huangboju** [comment]
Hey 
I solved
Check your build settings -> Other linker flags framework

**Comment by Jhonny12345** [comment]
What should I check in Other linker flags?

What do I need to add or remove in other linker flags? 

Please reply

**Comment by huangboju** [comment]
<img width="814" alt="2016-07-14 4 37 14" src="https://cloud.githubusercontent.com/assets/14818224/16833298/43ba81ea-49e1-11e6-9615-63d87ef1256f.png">

**Comment by Jhonny12345** [comment]
I already have that framework in other linker flags. But it is still not working.

**Comment by huangboju** [comment]
Delete workspace and podfile.lock
pod install

**Comment by Jhonny12345** [comment]
Thanks it is working now
