### ISSUE TITLE
PureLayout In App Extension Warning - `linking against a dylib` 

### ISSUE THREAD

**Issue by jch-duran** [PureLayout/PureLayout#141]
I'm learning how to add a Today Extension programmatically into my application. I have completed the [steps](https://github.com/PureLayout/PureLayout#using-carthage) to include PureLayout into my Xcode project using [Carthage](https://github.com/Carthage/Carthage#adding-frameworks-to-an-application), but I've stumbled across the following warning which I have been unable to satisfy: 

`Linking against a dylib which is not safe for use in application extensions: /Users/<User>/Desktop/<AppName>/Carthage/Build/iOS/PureLayout.framework/PureLayout`

Within my App Extension Target, in addition to defining the preprocessor macro PURELAYOUT_APP_EXTENSIONS to prevent usage of unavailable APIs as suggested from [PureLayout/Wiki/App-Extensions](https://github.com/PureLayout/PureLayout/wiki/App-Extension), I've also made sure to set “Require Only App-Extension-Safe API” build setting to Yes as Apple suggests [here](https://developer.apple.com/library/ios/documentation/General/Conceptual/ExtensibilityPG/ExtensionScenarios.html#//apple_ref/doc/uid/TP40014214-CH21-SW5) for the same reason. 

My question: Did I do the following noted above in the correct build target? And if not, to which target or targets should it be applied to?

Any help would be much appreciated, thank you!

**Comment by tonglil** [comment]
I have the same question, the warning still shows after setting the macro. Does this mean I have done it incorrectly?
