### ISSUE TITLE
Importing files using Carthage

### ISSUE THREAD

**Issue by zghotlawala** [PureLayout/PureLayout#146]
**\* Fetching PureLayout
**\* Checking out PureLayout at "v3.0.2"
**\* xcodebuild output can be found in /var/folders/nc/rgzzk0ln72x9gvhfg5c9kqjm0000gp/T/carthage-xcodebuild.oQePAE.log
**\* Building scheme "PureLayout_tvOS" in PureLayout.xcodeproj
xcodebuild: error: Unable to find a destination matching the provided destination specifier:
        { platform:tvOS Simulator, id:0EA34A5A-FAD1-4E3E-B342-87E6553EC479 }
/.../Carthage/Checkouts/PureLayout/PureLayout/PureLayout/PureLayout+Internal.h:32:9: warning: macro name is a reserved identifier [-Wreserved-id-macro]
/.../Carthage/Checkouts/PureLayout/PureLayout/PureLayout/PureLayout+Internal.h:32:9: warning: macro name is a reserved identifier [-Wreserved-id-macro]
/.../Carthage/Checkouts/PureLayout/PureLayout/PureLayout/PureLayout+Internal.h:32:9: warning: macro name is a reserved identifier [-Wreserved-id-macro]
A shell task (/usr/bin/xcrun xcodebuild -project /.../Carthage/Checkouts/PureLayout/PureLayout/PureLayout.xcodeproj -scheme PureLayout_tvOS -configuration Release -sdk appletvsimulator -destination platform=tvOS Simulator,id=0EA34A5A-FAD1-4E3E-B342-87E6553EC479 -destination-timeout 3 ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES clean build) failed with exit code 70:
xcodebuild: error: Unable to find a destination matching the provided destination specifier:
        { platform:tvOS Simulator, id:0EA34A5A-FAD1-4E3E-B342-87E6553EC479 }

It is showing empty in Cathage/Build. So I cannot import a framework. Thus I cannot use in the project.

Please suggest where i am mistaking.

**Comment by buscarini** [comment]
+1

**Comment by mickeyreiss** [comment]
Closing as this is old and should be covered by the other tvOS Carthage issues (#151, #163).
