### ISSUE TITLE
How to set Priority ?

### ISSUE THREAD

**Issue by Joe0708** [PureLayout/PureLayout#147]
Hello,
I have a problem with the project,
I want to set the same constraints to UIView, when setting different Priority, has been matched with different scenarios
But I found that setting priorities always lead to collapse and error message "Mutating a priority from required to not on an installed constraint (or vice-versa) is not supported. You passed priority 250 and the existing priority was 1000"
I was using the method set
AutoSetDimension:ALDimensionWidth toSize:50.f] setPriority:UILayoutPriorityDefaultLow] [[v;
How to solve this problem, thank you very much for your answer

**Comment by lkraider** [comment]
Use the `NSLayoutConstraint [autoSetPriority:forConstraints:]` block.
