### ISSUE TITLE
__NSMutableArray_of macro name is a reserved identifier

### ISSUE THREAD

**Issue by lkraider** [PureLayout/PureLayout#148]
When building PureLayout this warning is generated:
```
PureLayout/PureLayout+Internal.h:32:9: macro name is a reserved identifier [-Wreserved-id-macro]
▸ #define __NSMutableArray_of(type)                   PL__GENERICS(NSMutableArray, type)
▸         ^
```
Source:
https://github.com/PureLayout/PureLayout/blob/4f64fff84ebb0f78514eefc15368de21ea54cc87/PureLayout/PureLayout/PureLayout%2BInternal.h#L32

**Comment by mickeyreiss** [comment]
I'd be happy to pull in and release a fix for this warning.
