### ISSUE TITLE
How to use Purelayout with init() that requires parameters?

### ISSUE THREAD

**Issue by sebthiriet** [PureLayout/PureLayout#149]
Consider the following example:

```
let tableView: UITableView = {
        let t = UITableView(frame: CGRect(...), style: .Grouped) 
        return t
}()
```

I haven't found the way to use Purelayout with this kind of objects that requires an init() with parameters ?
This will not work:

```
let tableView: UITableView = {
        let t = UITableView.newAutoLayoutView()
        t.style = .Grouped   // this will not work 
        return t
}()
```

And if you have a custom object with convenience init(), you have the same problem :

```
convenience init(parameter1: CGFloat = 0, parameter2: Bool) {
      self.init()
}
let object: MyCustomObject = {
       let t = MyCustomObject(parameter1: 10, parameter2: true).newAutoLayoutView()   // does not work
       let t = MyCustomObject.newAutoLayoutView(parameter1: 10, parameter2: true)     // does not work
        return t
}()
```

I'm not the only one to face this type of problem, but no answer has been made yet on StackOverflow:
http://stackoverflow.com/questions/25849248/custom-uibutton-with-purelayout
http://stackoverflow.com/questions/33640924/using-purelayout-with-base-ui-class

Does someone can help?
I do a lot of subclasses on my project with convenience init ?

Thanks

**Comment by sebthiriet** [comment]
No answer from anyone? Is the question trivial?
Though, a search on stackoverflow shows that I'm not the only on to wonder how to cope with this...

Help if you can, I'm sure it will help newbies to PureLayout!

**Comment by lkraider** [comment]
Call the `init` method and then afterwards call `configureForAutoLayout` on the view.

**Comment by sebthiriet** [comment]
Thanks very much @lkraider for your answer.
I'll try that.
