### ISSUE TITLE
Not support swift3.0

### ISSUE THREAD

**Issue by immustard** [PureLayout/PureLayout#152]
First of all, I'm not good at English.
I find PureLayout is not support in swift3.0. Maybe I don't know how to use it.

**Comment by nithinreddygaddam** [comment]
I have the same concern.. Is it available for Swift 3.0?

**Comment by mickeyreiss** [comment]
I'd be happy to accept a pull request that adds Swift 3 support. @gabek, maybe you're up for the challenge?

**Comment by ppamorim** [comment]
It's working with me. But by some reason `NSConstraint` doesn't exist.

**Comment by lkraider** [comment]
Pull request #155 might help

**Comment by mickeyreiss** [comment]
#155 is now merged.
