### ISSUE TITLE
Release 3.1.0

### ISSUE THREAD

**Issue by mickeyreiss** [PureLayout/PureLayout#157]
Hello PureLayout contributors,

I'd love some help preparing cutting a release:
- [ ] 👍 confirmation that `master` is working in your projects and easy to upgrade
- [ ] Notes for the Github release
- [ ] Compatibility testing with various versions of Xcode/Swift/Objective-C/iOS/macOS/tvOS
- [ ] Fix travis-ci build (#156)
- [ ] Ensure all example apps build and render correctly
- [ ] Confirm that 3.1.0 is a sensible version number for this release

cc/ @lkraider @alanscarpa @btraut @kevinmcampos

**Comment by craigzour** [comment]
Hi @mickeyreiss ,

Any update on this release ? I would like to migrate my project to Swift3 :)

**Comment by qvacua** [comment]
@craigzour Using the current version of PureLayout (3.0.2) with Swift 3.0.1 and having no problem whatsoever. 👍

**Comment by mickeyreiss** [comment]
@craigzour No updates. I haven't been able to check any of the boxes. Voicing this request and providing feedback about `master` is helpful for giving me confidence to cut the release. Can you help with any of the points above?

**Comment by craigzour** [comment]
@mickeyreiss Unfortunately my project is too big. I would need weeks to migrate it to Swift 3 in order to test the "master" branch and I cannot afford that :-(

**Comment by aceontech** [comment]
I have been using the master branch in production with Swift 3 for a while now and haven't run into problems. Is there anything specific you need to check that first box?

**Comment by lkraider** [comment]
I am running on master with no issues for 3 months now.

**Comment by Lutzifer** [comment]
build is fixed
