### ISSUE TITLE
Support for iOS 10

### ISSUE THREAD

**Issue by nithinreddygaddam** [PureLayout/PureLayout#160]
Does Pure Layout work with iOS 10 without any problems?

**Comment by Ricardo1980** [comment]
Is anyone having issues with variable height cells under iOS 10?

**Comment by Ashleyjwsi** [comment]
i have  issues with variable height cells under iOS 10? cell taken proper height but subview are not visible.

**Comment by Ricardo1980** [comment]
Yep, me too. I think this is regarding hugging and compression priority. It seems Apple change some behaviour. If I manage to isolate the problem, I will upload a sample project.

**Comment by Ricardo1980** [comment]
After changing my minimum target from iOS 8 to iOS 9, now when I compile with iOS 10 SDK everything works.
I absolutely have no idea about the reason.
Try that and let us know.

**Comment by mickeyreiss** [comment]
PureLayout should support iOS 10. As a thin wrapper around auto layout, it is certainly subject to any changes in behavior that come from within UIKit.

From what I understand, Apple does strive for both source (API) as well as binary (ABI) stability. Therefore, it's possible that certain code paths change when you update your minimum target. This way, your app can only break when a developer recompiles it, but not when Apple releases a new version of iOS.

Please do open an issue if you have found any bugs in the past few months. Thanks!
