### ISSUE TITLE
layout animaiton is invalid

### ISSUE THREAD

**Issue by mistak** [PureLayout/PureLayout#168]
Before iOS 10, I had no problem with the layout animation, but after iOS 10, the layout animation was not valid. I made a demo to test it, and it didn't work.I've tried:
 [_label setNeedsUpdateConstraints];
 [_label updateConstraintsIfNeeded];
<img width="727" alt="2017-02-13 16 40 07" src="https://cloud.githubusercontent.com/assets/16186144/22876490/e1ae271c-f20b-11e6-8cc7-495516007f5e.png">

How to use layout animation?

**Comment by mistak** [comment]
@mickeyreiss

**Comment by mistak** [comment]
Do you know what's going on?

**Comment by nspavlo** [comment]
In this example `constraint.constant` value is zero. Subview is outside of visible bounds. Please correct me if I'm wrong.

```
@interface UITestViewController ()

@property (nonatomic, strong) NSLayoutConstraint *constraint;

@end

@implementation UITestViewController

- (void)viewDidLoad
{
    [super viewDidLoad];
    
    self.view.backgroundColor = [UIColor blackColor];
    
    UIView *view = [[UIView alloc] initForAutoLayout];
    view.backgroundColor = [UIColor greenColor];
    [self.view addSubview:view];
    
    [view autoPinEdgeToSuperviewEdge:ALEdgeBottom];
    [view autoSetDimensionsToSize:CGSizeMake(200, 200)];
    self.constraint = [view autoPinEdge:ALEdgeLeft toEdge:ALEdgeRight ofView:self.view];
}

- (void)touchesBegan:(NSSet<UITouch *> *)touches withEvent:(UIEvent *)event
{
    self.constraint.constant = -200;
    
    [self.view setNeedsUpdateConstraints];
    [self.view updateConstraintsIfNeeded];
    
    [UIView animateWithDuration:0.25 animations:^{
        [self.view layoutIfNeeded];
    }];
}

@end
```

**Comment by mistak** [comment]
I have solved the problem in iOS 10,My method is only layoutIfNeed it's superview,before iOS 10 ,i just layout itself.
