### ISSUE TITLE
ALAxisVertical: NSLayoutAttributeCenterX, ALAxisHorizontal: NSLayoutAttributeCenterY

### ISSUE THREAD

**Issue by egarlock** [PureLayout/PureLayout#170]
I believe these are mixed up in the `NSLayoutConstraint+PureLayout.m` file. I believe the correct values should be:

    case ALAxisVertical:
        layoutAttribute = NSLayoutAttributeCenterY;
        break;
    case ALAxisHorizontal:
        layoutAttribute = NSLayoutAttributeCenterX;
        break;

**Comment by mickeyreiss** [comment]
I don't think this is the case.

From `PureLayoutDefines.h`:
```objc
129     /** A vertical line equidistant from the view's left and right edges. */                                                                                                                   
130     ALAxisVertical = NSLayoutAttributeCenterX,                                                                                                                                                 
131     /** A horizontal line equidistant from the view's top and bottom edges. */                                                                                                                 
132     ALAxisHorizontal = NSLayoutAttributeCenterY,                                                                                                                                               
```
Regardless of possible ergonomic improvements, we can't change this due to compatibility.

**Comment by garamsongwheels** [comment]
I do believe @egarlock was correct, after having spent a few hours debugging this.

This code below results in the image below:
```
    [NSLayoutConstraint autoSetPriority:999 forConstraints:^{
        [itView autoSetContentCompressionResistancePriorityForAxis:ALAxisHorizontal];
    }];
```
![image](https://user-images.githubusercontent.com/41492448/63906881-4899dd80-c9ce-11e9-85ca-7ad8f0040eaf.png)

While this code below results in the image below:
```
    [NSLayoutConstraint autoSetPriority:777 forConstraints:^{
        [itView autoSetContentCompressionResistancePriorityForAxis:ALAxisVertical];
    }];
```
![image](https://user-images.githubusercontent.com/41492448/63906952-72530480-c9ce-11e9-8d61-ed346634b7be.png)

**Comment by garamsongwheels** [comment]
@mickeyreiss
