### ISSUE TITLE
Returned NSLayoutConstraint array order

### ISSUE THREAD

**Issue by rerelease** [PureLayout/PureLayout#171]
I find it convenient to occasionally store one of the several returned constraints from the array as a member, to change it later

`contentViewBottom = contentView.autoPinEdgesToSuperviewEdges()[2]`

This is done with the assumption that edge constraints are returned in the order top-leading-bottom-trailing, like `UIEdgeInsets` initializer.

Is it sensible to rely on this ordering and if so, could it be documented?

**Comment by mickeyreiss** [comment]
Yes, this ordering is part of the API contract. I'd be happy to merge in a PR that updates the docs or adds unit tests for this.
