### ISSUE TITLE
Auto set identifier and create constraints best practice

### ISSUE THREAD

**Issue by revolter** [PureLayout/PureLayout#173]
If I want to create some constraints with a custom identifier, do I need to write it like this:

    [NSLayoutConstraint autoSetIdentifier:@"custom identifier" forConstraints:^{
        [NSLayoutConstraint autoCreateAndInstallConstraints:^{
            // constraints
        }];
    }];

or only:

    [NSLayoutConstraint autoSetIdentifier:@"custom identifier" forConstraints:^{
        // constraints
    }];

?

**Comment by revolter** [comment]
@mickeyreiss, @smileyborg, help?

**Comment by mickeyreiss** [comment]
Either one will usually work. It depends on when you'd like each constraint to be installed.

**Comment by revolter** [comment]
So if I only set one constraint, I can ditch the `autoCreateAndInstallConstraints:` method call and it will be correctly installed, right?

**Comment by mickeyreiss** [comment]
Yes, that's right to the best of my knowledge.
