### ISSUE TITLE
Plans to support iOS 11's safeAreaLayoutGuide 

### ISSUE THREAD

**Issue by jsonfellin** [PureLayout/PureLayout#199]
Title says it all.

**Comment by Arnoymous** [comment]
.autoPinEdge(toSuperviewMargin:) work with safearea

**Comment by Arnoymous** [comment]
.autoPin(toTopLayoutGuideOf: <#T##UIViewController#>, withInset:)
.autoPin(toBottomLayoutGuideOf: <#T##UIViewController#>, withInset:)

work with statusbar & home button

**Comment by toohotz** [comment]
#203

**Comment by lwdupont** [comment]
Released with 3.1.2: https://github.com/PureLayout/PureLayout/releases
