### ISSUE TITLE
3.0.2 tvOS failed to compile

### ISSUE THREAD

**Issue by XiongCaixing** [PureLayout/PureLayout#200]
Compile PureLayout using Carthage, tvOS failed to compile.
xcodebuild: error: Unable to find a destination matching the provided destination specifier:
		{ platform:tvOS Simulator, id:0BE51815-BA3D-4AA6-BBAB-3612618ECA7B }

	Ineligible destinations for the "PureLayout_tvOS" scheme:
		{ platform:tvOS, id:dvtdevice-DVTiOSDevicePlaceholder-appletvos:placeholder, name:Generic tvOS Device }
		{ platform:tvOS Simulator, id:dvtdevice-DVTiOSDeviceSimulatorPlaceholder-appletvsimulator:placeholder, name:Generic tvOS Simulator Device }

**Comment by jbouaziz** [comment]
@XiongCaixing have you ever been able to find a solution for that?

**Comment by XiongCaixing** [comment]
I didn't find a solution, Only compile iOS @jbouaziz

**Comment by lwdupont** [comment]
Is it just via Carthage? I compiled the tvOS example a few days ago with no issues.
