### ISSUE TITLE
some error in iOS10 

### ISSUE THREAD

**Issue by sunstrider12** [PureLayout/PureLayout#202]
in cell
kHeadSize=50  kCellPadding=8
icon is UIImageView   number,name,carlos is UILabel
    [self.contentView autoPinEdgesToSuperviewEdges];

    [_icon autoPinEdgesToSuperviewEdgesWithInsets:UIEdgeInsetsMake(kCellPadding, kCellPadding, kCellPadding, kCellPadding) excludingEdge:ALEdgeRight];
    [_icon autoSetDimensionsToSize:CGSizeMake(kHeadSize, kHeadSize)];
    
    [_number autoConstrainAttribute:ALAttributeRight toAttribute:ALAttributeRight ofView:_icon];
    [_number autoPinEdge:ALEdgeBottom toEdge:ALEdgeBottom ofView:_icon];
    [_number autoSetDimensionsToSize:CGSizeMake(20, 14)];

    [_name autoAlignAxis:ALAxisHorizontal toSameAxisOfView:_icon];
    [_name autoPinEdge:ALEdgeLeft  toEdge:ALEdgeRight ofView:_icon withOffset:kPadding];
    
    [_carlos autoPinEdgeToSuperviewEdge:ALEdgeRight withInset:kPadding];
    [_carlos autoAlignAxisToSuperviewAxis:ALAxisHorizontal];

warning:
[LayoutConstraints] Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. 
	Try this: 
		(1) look at each constraint and try to figure out which you don't expect; 
		(2) find the code that added the unwanted constraint or constraints and fix it. 
(
    "<NSLayoutConstraint:0x17028fc30 V:|-(8)-[UIImageView:0x1019eae70]   (active, names: '|':UITableViewCellContentView:0x1019b4060 )>",
    "<NSLayoutConstraint:0x17028fd70 UIImageView:0x1019eae70.bottom == UITableViewCellContentView:0x1019b4060.bottom - 8   (active)>",
    "<NSLayoutConstraint:0x17028f9b0 UIImageView:0x1019eae70.height == 50   (active)>",
    "<NSLayoutConstraint:0x17028eba0 'UIView-Encapsulated-Layout-Height' UITableViewCellContentView:0x1019b4060.height == 66.5   (active)>"
)

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x17028f9b0 UIImageView:0x1019eae70.height == 50   (active)>

Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKit/UIView.h> may also be helpful.

how to fix it? thinks

**Comment by lwdupont** [comment]
@sunstrider12 did you try setting a breakpoint on UIViewAlertForUnsatisfiableConstraints and see which line might cause the issue? That should allow you to find the line of code.
