### ISSUE TITLE
autoPinEdgeToSuperviewMargin:withInsets doesn't exist.

### ISSUE THREAD

**Issue by gngrwzrdsb** [PureLayout/PureLayout#204]
Would be nice if you could add this real quick:

autoPinEdgeToSuperviewMargin:withInsets:

It's documented in the readme but I can't find it anywhere.

**Comment by toohotz** [comment]
Will make a PR to add both

- `(NSLayoutConstraint *)autoPinEdgeToSuperviewMargin:(ALEdge)edge withInset: (CGFloat)inset`

- `(NSLayoutConstraint *)autoPinEdgesToSuperviewMarginWithInsets:(ALEdgeInsets)insets`

**Comment by toohotz** [comment]
PR #210 Is up if you want to take a look @gngrwzrdsb.

**Comment by revolter** [comment]
@thuytien140894, A new version that includes these was released 4 hours ago. Could you please try it and close this issue if it's working correctly for you?
