### ISSUE TITLE
Add support for Swift Package Manager

### ISSUE THREAD

**Issue by oopsFrogs** [PureLayout/PureLayout#213]
I try to use swift package manager to resolve PureLayout, but a "no manifest error" occur.
I wonder is is possible to support swift package manager?

**Comment by kylebrowning** [comment]
Anything happening here?

**Comment by lvnkmn** [comment]
I gave it a try, but failed with the limited time I had for this. I didn't manage to get the package built. However only later I found [this](http://ankit.im/swift/2016/05/21/creating-objc-cpp-packages-with-swift-package-manager/) link, which shows how it, maybe someone else can pick it up, since I'm currently too busy for this.

**Comment by dengladyshev** [comment]
I added #244 pull-request, please look, it works.

**Comment by ruizmarc** [comment]
Any updates on the pull request acceptance? It would be great to use this with SPM! :D

**Comment by lwdupont** [comment]
I merged it, I'll try to release it in the next few days.

**Comment by ruizmarc** [comment]
Hi! I tried to use master branch with swift package manager, so I can use PureLayout with SPM, but I'm always getting this kind of errors in all places where I use PureLayout: `Value of type 'UIStackView' has no member 'autoPinEdge'`. 

With CocoaPods is working fine. 

Is there something wrong with the SMP definition, or am I doing something wrong?

**Comment by ruizmarc** [comment]
After a few investigation, I found this discussion: https://forums.swift.org/t/swift-package-manager-for-objc-targets/25968/10

It seems it is related with the project structure, as by default XCode looks for the include folder

**Comment by dolzhenko-tony** [comment]
Check this: https://github.com/masatomizuta/PureLayout/tree/fix-swiftpm seems to be working

**Comment by ruizmarc** [comment]
Hi @dolzhenko-tony , it seems it is working fine for me in XCode 11.4.1 :)

Thanks for the sharing! 

PS: Maybe a pull-request would help more people in my same situation

**Comment by dolzhenko-tony** [comment]
@ruizmarc here we go: #248  Hopefully we could have it merged soon.

**Comment by lwdupont** [comment]
I just merged it.
