### ISSUE TITLE
Crash on autoPinEdgesToSuperviewEdges

### ISSUE THREAD

**Issue by mmower** [PureLayout/PureLayout#216]
In my Window controller, -windowDidLoad:

```
  NSInteger index;
  index = [_tabView indexOfTabViewItemWithIdentifier:@"prototypes"];
  if( index != NSNotFound ) {
    NSView *view = _propertiesViewController.view;
    if( view ) {
      view.translatesAutoresizingMaskIntoConstraints = NO;
      [[_tabView tabViewItemAtIndex:index] setView:view];
      [view autoPinEdgesToSuperviewEdges];
    }
  }
```

This is throwing an exception:

> 2018-06-12 00:13:07.017293+0100 Mentat[6071:345014] [General] An uncaught exception was raised
> 2018-06-12 00:13:07.017380+0100 Mentat[6071:345014] [General] NSLayoutConstraint for <NSView: 0x600000124060>: A multiplier of 0 or a nil second item together with a location for the first attribute creates an illegal constraint of a location equal to a constant. Location attributes must be specified in pairs.
> 2018-06-12 00:13:07.022732+0100 Mentat[6071:345014] [General] (
> 	0   CoreFoundation                      0x00007fffc3efc2cb __exceptionPreprocess + 171
> 	1   libobjc.A.dylib                     0x00007fffd8d1748d objc_exception_throw + 48
> 	2   CoreFoundation                      0x00007fffc3f7ac3d +[NSException raise:format:] + 205
> 	3   Foundation                          0x00007fffc5b3a436 ResolveConstraintArguments + 853
> 	4   Foundation                          0x00007fffc58b9a51 +[NSLayoutConstraint constraintWithItem:attribute:relatedBy:toItem:attribute:multiplier:constant:] + 84
> 	5   PureLayout                          0x0000000100401143 -[NSView(PureLayout) autoConstrainAttribute:toAttribute:ofView:withOffset:relation:] + 168
> 	6   PureLayout                          0x00000001004009b5 -[NSView(PureLayout) autoPinEdgeToSuperviewEdge:withInset:relation:] + 160
> 	7   PureLayout                          0x0000000100400a69 -[NSView(PureLayout) autoPinEdgesToSuperviewEdgesWithInsets:] + 67
> 	8   PureLayout                          0x0000000100400a20 -[NSView(PureLayout) autoPinEdgesToSuperviewEdges] + 67
> 	9   Mentat                              0x0000000100023c24 -[MNExplorerWindowController windowDidLoad] + 356
> 	10  AppKit                              0x00007fffc19d9c78 -[NSWindowController _windowDidLoad] + 682

I'm sure it's something I am missing but given that I've turned off autoresizing masks and am pinning all edges I am not sure where an illegal constraint is coming from.

Can anyone suggest where I might have gone wrong? Or have I fallen over a bug?

Many thanks.

Matt

**Comment by mmower** [comment]
Okay I thought I had it, I'd goofed with getting the properties and prototypes view controllers mixed up. But I hadn't switched through the views. The error is still there.

**Comment by toohotz** [comment]
Lol no worries, so from the crash log the key point that I'm seeing is this guy *nil second item together* so your `NSView` that you're referencing is coming from your `_propertiesViewController.view`.  Given that it seems to be the view of a `UIViewController` I would like to assume that the superview of the view should not be nil but the first item of the constraint equation referring to this view that is looking to pin to the edges of its superview with the superview being the second item in the constraint equation seems to be nil.  So looking at the exception being thrown, can you confirm that the `NSView` of the props VC that you have does indeed have a superview?

**Comment by mmower** [comment]
My bad. Shouldn't code when tired. I forgot that I was replacing the tabView view not adding to it, hence no constraints required. The original mistake I made (getting them the wrong way around) blinded me to the real problem.
