### ISSUE TITLE
PureLayoutVersionNumber

### ISSUE THREAD

**Issue by AppHock** [PureLayout/PureLayout#230]
Anybody know how to get PureLayoutVersionNumber value?

Undefined symbols for architecture arm64:
  "_PureLayoutVersionString", referenced from:
      -[AppDelegate application:didFinishLaunchingWithOptions:] in AppDelegate.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by lwdupont** [comment]
Are you using Swift or Objective C for this?
