### ISSUE TITLE
Cell auto Height

### ISSUE THREAD

**Issue by hellogaojun** [PureLayout/PureLayout#231]
Hello,the purelayout can not calculate UItableViewCell height automaticly in iOS8 later,Why?

**Comment by hellogaojun** [comment]
I am so sorry,Maybe I did not write a suitable constraint last time.And I wrote a demo about cell auto height int three ways,such as xib, masonry,purelayout. The link is https://github.com/hellogaojun/tableAutoHeight.git

**Comment by lwdupont** [comment]
I tried your example, it doesn't compile with Xcode 10.1. But if you see #234 you'll see some suggestions, a very similar issue. I don't think there's an issue in PureLayout yet though. :)
