### ISSUE TITLE
Unable to find a specification for `PureLayout`

### ISSUE THREAD

**Issue by javidsheikh** [PureLayout/PureLayout#233]
I'm getting this error when running pod install with `pod 'PureLayout'` in my Podfile:

````Unable to find a specification for `PureLayout````

 I checked your podspec and it looks fine. Can you see what the problem is?
Many thanks in advance!

**Comment by lwdupont** [comment]
Try doing a pod repo update: https://guides.cocoapods.org/terminal/commands.html#pod_repo_update

I just installed it on a project this morning :)
