### ISSUE TITLE
Apply greater than or equal to constraints in Purelayout?

### ISSUE THREAD

**Issue by mohsinsurani1** [PureLayout/PureLayout#235]
As TableView height can differ. To limit the size its top and bottom constraints is required. I want them to give "greater than or equal to" using purelayout.

**Comment by mohsinsurani1** [comment]
Can I get an example code of applying it?

**Comment by dragonetail** [comment]
Please try APIs like the following:
subView.autoPinEdge(toSuperviewSafeArea: .top, withInset: 10, relation: .greaterThanOrEqual)
