### ISSUE TITLE
Dynamic cell height in pure layout

### ISSUE THREAD

**Issue by artworkad** [PureLayout/PureLayout#24]
![bildschirmfoto 2014-11-06 um 19 23 12](https://cloud.githubusercontent.com/assets/524580/4941359/1980b474-65e2-11e4-9dc5-96ca572a0c04.png)

I want the table cell to grow depending on the content. As you can  see from this picture the first cell has a big gap. I pretty much used your https://github.com/smileyborg/TableViewCellWithAutoLayoutiOS8 project.

The only thing I changed was

```
titleLabel.numberOfLines = 1
```

to 

```
titleLabel.numberOfLines = 0
```

because the title may have variable length. And I get the result like you see in the picture. Any ideas whats wrong? Maybe the constrains don't find my use case?

```
titleLabel.autoPinEdgeToSuperviewEdge(.Top, withInset: kLabelVerticalInsets)
titleLabel.autoPinEdgeToSuperviewEdge(.Leading, withInset: kLabelHorizontalInsets)
titleLabel.autoPinEdgeToSuperviewEdge(.Trailing, withInset: kLabelHorizontalInsets)

bodyLabel.autoPinEdge(.Top, toEdge: .Bottom, ofView: titleLabel, withOffset: 10.0, relation: .GreaterThanOrEqual)

bodyLabel.autoPinEdgeToSuperviewEdge(.Leading, withInset: kLabelHorizontalInsets)
bodyLabel.autoPinEdgeToSuperviewEdge(.Trailing, withInset: kLabelHorizontalInsets)
bodyLabel.autoPinEdgeToSuperviewEdge(.Bottom, withInset: kLabelVerticalInsets)
```

any ideas?

**Comment by engmsaleh** [comment]
Please consider using this lib as it have more elegant, clean code and more stable than @smileyborg solution 
https://github.com/forkingdog/UITableView-FDTemplateLayoutCell
