### ISSUE TITLE
3.1.5 is not on CocoaPods

### ISSUE THREAD

**Issue by alexito4** [PureLayout/PureLayout#242]
Hi @toohotz, the release https://github.com/PureLayout/PureLayout/releases/tag/3.1.5 doesn't show up on CocoaPods yet. 

The Podspec seems fine, but checking the Specs repo looks like it hasn't been updated https://github.com/CocoaPods/Specs/tree/master/Specs/9/7/f/PureLayout

Any plans to update it?

Thanks

**Comment by xuefan-eero** [comment]
is this out yet?

**Comment by lwdupont** [comment]
Sorry @toohotz totally missed this. I'll release it tomorrow morning pacific.

**Comment by xuefan-eero** [comment]
thank you!!

**Comment by lwdupont** [comment]
Thanks for the reminder @xuefan-eero . Done:

--------------------------------------------------------------------------------
 🎉  Congrats

 🚀  PureLayout (3.1.5) successfully published
 📅  September 26th, 15:28
 🌎  https://cocoapods.org/pods/PureLayout
 👍  Tell your friends!
--------------------------------------------------------------------------------
