### ISSUE TITLE
Fix deployment target warning in Swift Package Manager for Xcode 12

### ISSUE THREAD

**Issue by AlexNsbmr** [PureLayout/PureLayout#251]
Would it be possible to fix the warning

`The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.0.99.`

Xcode version: 12.0
Installation method: SPM

Thank you

**Comment by toohotz** [comment]
This should be resolved in PR #253.  If you're still running into issues feel free to re open this issue.
