### ISSUE TITLE
SPM: Xcode 12.5 Swift 5.4: Umbrella header for module 'PureLayout' does not include header 'PureLayout+Internal.h"

### ISSUE THREAD

**Issue by bounds** [PureLayout/PureLayout#256]
New to how SPM resolves Objective-C packages in Xcode 12.5, any header present in what it assumes is the "umbrella header" (in this case `PureLayout.h` as it matches the name of the package) seems to be required to include the headers in `publicHeadersPath`.

As there is an internal header in there and (rightfully) it isn't meant to be included in the umbrella header, I suggest either moving the internal header elsewhere or (not entirely sure if it would work) exclude the internal header in an `excludes` parameter. 

Happy to make a PR for this.

![image](https://user-images.githubusercontent.com/7019497/116298789-841c1a80-a762-11eb-9186-e125f9a4a1b3.png)

**Comment by bounds** [comment]
Thank you @toohotz for the merge. Any chance we can bump the version to support this in SPM? Our team is still using my fork as of now and would prefer to switch back to this repo again.

**Comment by toohotz** [comment]
@bounds no problem, was away for a bit but just released. - https://github.com/PureLayout/PureLayout/releases/tag/3.1.9
