### ISSUE TITLE
Cannot install latest release (3.1.9) with CocoaPods

### ISSUE THREAD

**Issue by jhicks-ddm** [PureLayout/PureLayout#258]
I can only install the previous release (3.1.8). The only thing I can see is that you tagged 3.1.9 as `3.1.9` instead of `v3.1.9`. Perhaps that is the reason it can't be installed.

**Comment by pcki11** [comment]
Also, version string was not incremented in the podspec:
`s.version               = '3.1.8'`

**Comment by toohotz** [comment]
Issue was as @pcki11 stated, forgot to bump up the podspec version.  Just pushed the changes, you should be able to update now without an issue.

**Comment by Unknoob** [comment]
Version 3.1.9 is still not available on Cocoapods.
https://cocoapods.org/pods/PureLayout

**Comment by toohotz** [comment]
@Unknoob Realized I didn't push the actual podspec to trunk.  Done now and is updated.
