### ISSUE TITLE
NSArray+PureLayout.m produces an error when added to app extension target

### ISSUE THREAD

**Issue by zhxnlai** [PureLayout/PureLayout#30]
This block of code from NSArray+PureLayout.m

``` objective-c
#if TARGET_OS_IPHONE
    BOOL isRightToLeftLayout = [[UIApplication sharedApplication] userInterfaceLayoutDirection] == UIUserInterfaceLayoutDirectionRightToLeft;
#else
    BOOL isRightToLeftLayout = [[NSApplication sharedApplication] userInterfaceLayoutDirection] == NSUserInterfaceLayoutDirectionRightToLeft;
#endif /* TARGET_OS_IPHONE */
    BOOL shouldFlipOrder = isRightToLeftLayout && (axis != ALAxisVertical); // imitate the effect of leading/trailing when distributing horizontally
```

produces the following error when added to app extension target:

> /Users/zhixuanlai/Developer/Github/Emotic/Emotic/Emotic/Source/NSArray+PureLayout.m:383:48: 'sharedApplication' is unavailable: not available on iOS (App Extension) - Use view controller based solutions where appropriate instead.

**Comment by evenluo** [comment]
So I put the hook at the end of my Podfile, Got this:

undefined method `projects' for #<Pod::Installer:0x007fb62a9aad98>

**Comment by evenluo** [comment]
And here is the solution: 
https://github.com/CocoaPods/CocoaPods/issues/3747

> you probably just want to change project to pods_project

Looks like the new CocoaPods version 0.38.0 has this issue.

**Comment by smileyborg** [comment]
Hi @evenluo,

You're correct, CocoaPods 0.38 has a breaking change in how the `post_install` hook works. I will update the [wiki page](https://github.com/smileyborg/PureLayout/wiki/App-Extensions) with the new syntax.

Thanks!
