### ISSUE TITLE
Add parameter to add priority onto constraint

### ISSUE THREAD

**Issue by mergesort** [PureLayout/PureLayout#8]
In iOS 7, it was possible to create an NSLayoutConstraint and then modify it's `priority` property after it was added to a view.

For example you could do:

```
NSLayoutconstraint *labelConstraint = [myView autoPinEdgeToSuperviewEdge:ALEdgeTop withInset:0];
labelConstraint.priority = UILayoutPriorityDefaultLow;
```

In iOS 8, this will throw an NSInternalInconsistencyException, saying `Mutating a priority from required to not on an installed constraint (or vice-versa) is not supported`

The solution is to add the priority before calling `autoInstall`. To do this, I would recommend adding priority as a parameter that you can pass in when auto creating a constraint. 

I've had to switch back to doing manual constraints for now, but if I am correct, that would fix the crashes. Let me know if you need any more information, love the library.

**Comment by ianbytchek** [comment]
@mergesort took me sometime to figure this out for AppKit, this works pretty well:

```swift
extension NSView
{
    public func autoPinEdge(edge: ALEdge, toEdge: ALEdge, ofView: NSView, priority: NSLayoutPriority) -> NSLayoutConstraint {
        var constraint: NSLayoutConstraint!

        NSLayoutConstraint.autoSetPriority(priority) {
            constraint = self.autoPinEdge(edge, toEdge: toEdge, ofView: ofView)
        }

        return constraint
    }

    public func autoPinEdgeToSuperviewEdge(edge: ALEdge, priority: NSLayoutPriority) -> NSLayoutConstraint {
        var constraint: NSLayoutConstraint!

        NSLayoutConstraint.autoSetPriority(priority) {
            constraint = self.autoPinEdgeToSuperviewEdge(edge)
        }

        return constraint
    }
}
```
