### ISSUE TITLE
PureLayout needs a new maintainer!

### ISSUE THREAD

**Issue by smileyborg** [PureLayout/PureLayout#80]
Due to [upcoming changes in my employment](https://twitter.com/smileyborg/status/633323032002465792), I will no longer be able to serve as the maintainer for PureLayout. :disappointed:

**Fortunately, PureLayout has [never been in better shape](https://github.com/smileyborg/PureLayout/releases/tag/v3.0.0), and I see an extremely bright future ahead for the library!** ☀️ This project is **not** being deprecated (it's a core dependency for thousands of developers and apps of all sizes)!

I'm actively seeking **one or more people** who are passionate about the project and are interested in taking on responsibility as a maintainer.

What responsibilities do(es) the maintainer(s) have?
* Complete control over the future direction of the project
* Full commit access to and ownership of the GitHub repository
* Maintaining the existing project & codebase (testing with new iOS and OS X releases, fixing any issues, etc)
* Updating the [official CocoaPod](https://cocoapods.org/pods/PureLayout) with new versions
* Responding to GitHub Issues and Pull Requests
* Reaping all of the praise and recognition that comes along with the above :smiley:

I would estimate that the minimum average weekly time commitment is about 1 hour -- not very large. Of course, there's the opportunity to invest more, depending on what you want to do with the project.

Part of this transition will be [moving](https://help.github.com/articles/transferring-a-repository/) PureLayout to a new home in the [PureLayout GitHub org](https://github.com/PureLayout).

Please post here if you're interested or want to learn more! It would be great if you could include some background on you, as well as your familiarity/experience with PureLayout.

I'd like to have at least one new maintainer selected by **September 1, 2015**.

**Comment by mickeyreiss** [comment]
I'd be happy to take this on. As a maintainer of PureLayout, I'll shepherd the codebase and help facilitate our communal development effort as transparently as possible.

Until we have other potential maintainers expressing interest here, I'll leave it at that :)

**Comment by smileyborg** [comment]
:+1: Thanks Mickey!

Everyone else: please continue to post here! I'm definitely going to leave this request open for at least a week to gather interest, then we can figure out how to move forward with those folks.

Also, I hope this goes without saying, but you don't have to be an official maintainer to contribute to the project!!

**Comment by chrisballinger** [comment]
Thank you all for the great work that has gone into this library! I use it in almost all of my apps. :)

**Comment by somethingkindawierd** [comment]
@smileyborg What kind of a time commitment do you see this requiring for the project to remain successful? Judging by the repo history it looks like you are the primary contributor and you’ve been fairly consistent in your work on it.

**Comment by danie11am** [comment]
Wow, that's sad to hear. Indeed, thanks for all the work you put into this. I love using PureLayout.

I've been using PureLayout for a couple of projects (when it was still a UIView category I believe?). I want to get involved and see what I can do, but I have never maintained an open source library, and tight on time as well. I'm happy to learn though. More about me: http://daniellam.me

**Comment by smileyborg** [comment]
@somethingkindawierd As I mentioned in the original post, I expect about an hour per week on average to be sufficient. The current version of the library is extremely stable and unlikely to need any fixes or time sensitive work. There are some weeks where I don't even have to think about or visit the GitHub project, it's that good! (Especially considering the popularity of this library -- for a sense of the scale, consider that it has ~10% the active users of the unbelievably popular [AFNetworking](https://cocoapods.org/pods/AFNetworking), based on the newly-released [CocoaPods stats](https://cocoapods.org/pods/PureLayout).) Most of my time as maintainer goes towards things like:

* Responding to issues/PRs
* Updating the README
* Updating the example apps and demos (e.g. for compatibility with new Xcode versions, new Swift syntax, etc)
* Fixing minor issues around environment/tooling (e.g. CocoaPods Podfile syntax changes, Travis CI environment changes, etc)

Generally I have targeted one major release of PureLayout per new iOS SDK release. Usually this is to adopt new SDK features and changes. So any major changes or new API added to the codebase is work done more or less once per year. With that said, if I were to continue to maintain the project, I expect the magnitude and scope of changes would continue to decrease -- v3.0 is a smaller release than v2.0 was, and v2.0 was of course smaller than the original v1.0 (adapted from UIView+AutoLayout). This is expected as both Apple's Auto Layout SDK and PureLayout mature. I don't think that PureLayout needs to continue adding more shiny new things to remain successful -- in fact, I attribute much of its success to the design decisions made to avoid unnecessary bloat and scope creep.

If you are curious to know my thoughts on the future of third-party Auto Layout libraries:
* PureLayout remains an excellent choice for apps already using it, apps with mixed codebases of Objective-C and Swift, and apps with the need to support earlier versions of iOS and OS X.
* I think there is a significant opportunity for a new third-party library (usable from both Swift and Objective-C) that is the spiritual successor to PureLayout, which assumes a deployment target of iOS 9.0 and OS X 10.11, and can then leverage the new NSLayoutAnchor APIs. Those new layout anchors are really great, and this new third-party library can build on top of those to offer some of the features that PureLayout does (but Apple's NSLayoutAnchor API does not) like automatically activating constraints, providing some helper APIs that create multiple constraints at once for common use cases (e.g. centering a view, pinning edges to superview's edges, etc). But this new third-party library would be able to be even more minimal than PureLayout, because it can build on top of the higher-level layout anchor API. Happy to share more thoughts around this.
* For pure Swift apps, I don't think you can beat [Cartography](https://github.com/robb/Cartography). Swift's malleable syntax and other language features enable some awesome possibilities that Cartography really takes advantage of. (Major props to @robb for building it.)

**Comment by smileyborg** [comment]
@danie11am Awesome! It sounds like you may be interested in contributing to the project without having to be one of the official maintainers?

Contributing can look like:
* Fixing bugs, making enhancements, building new API, etc in the codebase and submitting pull requests to have these changes integrated
* Contributing to unit test development (#1)
* Helping take care of tasks like updating the README, Travis CI, Code Coverage/Slather integrations, etc
* Participating in discussions about upcoming changes, features, and releases (via GitHub Issues)
* Helping respond to questions and other comments left by others as new Issues on the GitHub project

This would mean you don't have any required time commitment and can learn the ropes by participating, without having sole responsibility.

**Comment by danie11am** [comment]
@smileyborg yes sounds good! I'll start with that, and later on if @mickeyreiss needs more help for the  maintainer role I can consider to join as well.

**Comment by mickeyreiss** [comment]
That sounds like a good plan to me, @danie11am.

**Comment by pronebird** [comment]
@smileyborg you will not be forgotten!

**Comment by Bogidon** [comment]
@smileyborg I've always wanted to express my gratitude, but didn't find the right moment. Here it is though. Thanks for building PureLayout, it's gotten me through a lot! @mickeyreiss I will try to contribute as well.

**Comment by openaphid** [comment]
I would like to join the maintenance team or contribute in other ways. 

PureLayout was introduced into all our iOS products(15M+ daily users now) a year ago to solve the verbosity issue of AutoLayout. We appreciate a lot for the improved development efficiency. 

Wish you great success in UIKit team. Hope we can get an evolved layout system in future which doesn't hurt performance on complex UITableViewCells and no crashes on mis-configured layout parameters.

**Comment by smileyborg** [comment]
@openaphid That's really cool to hear, very impressive! Please share your thoughts if you have any specific ways that you want to be involved.

**Comment by smileyborg** [comment]
For those of you expressing interest in contributing, there's a new issue (#84) that would make a great first PR! I recommend posting there if you want to take it on so we know you'll be working on it.

**Comment by smileyborg** [comment]
Thanks again to everyone who expressed interest in contributing to the future of PureLayout (and to those who shared their thanks as well)!

I just moved PureLayout to its new home in the PureLayout GitHub organization (https://github.com/PureLayout), which means this is the new URL for the official PureLayout repository:

**https://github.com/PureLayout/PureLayout**

Because this was done by transferring the GitHub repository from my user account to the new PureLayout organization, GitHub automatically sets up a redirect so that all visitors to the old URL (https://github.com/smileyborg/PureLayout) are automatically redirected to the new location. More importantly, all existing git operations (`git clone`, `git pull`, etc) also redirect automatically from the old URL to the new one. So this move should be completely seamless for everyone.

Next, I'm happy to announce that @mickeyreiss will be the new maintainer for PureLayout! :balloon: He'll be taking over the responsibilities outlined above starting later this week. I've worked closely with Mickey for many years, and he has deep experience developing & maintaining third-party SDKs & frameworks for iOS at Braintree.

For everyone else who expressed interest in contributing or otherwise being involved in the project, I encourage you to take on some of the [suggestions I posted earlier in this thread](https://github.com/PureLayout/PureLayout/issues/80#issuecomment-132283190) for ways you can do that. I know that Mickey will appreciate any help and contributions from the community, and he'll be looking to hear your thoughts & opinions on the future direction of the project.

Finally, I personally won't be available much during the month of September, as I am traveling abroad. I will be following things and catching up when I can though. I'm looking forward to see where PureLayout goes from here!

:beers: :octocat:

**Comment by mickeyreiss** [comment]
Thanks, @smileyborg! Here's a :dollar: for the balloon.

I'm looking forward to working keeping the project alive and well.

As always, everyone should feel welcome to open a new issue for questions, comments and concerns!
