### ISSUE TITLE
autoPinEdge: order

### ISSUE THREAD

**Issue by hisavali** [PureLayout/PureLayout#92]
In the ALiOSDemo1ViewController, There are two views red & blue.

I was expecting same layout for following two calls which should be same in my opinion:

    [self.redView autoPinEdge:ALEdgeLeft toEdge:ALEdgeRight ofView:self.blueView withOffset:30];
    [self.blueView autoPinEdge:ALEdgeRight toEdge:ALEdgeLeft ofView:self.redView withOffset:30];

First call produces layout as expected:
   ![ios simulator screen shot 9 sep 2015 17 46 06](https://cloud.githubusercontent.com/assets/2108707/9768447/b3a25884-571b-11e5-830f-2cb46fb2cd23.png)

However second call produces layout which is bit odd. 
![ios simulator screen shot 9 sep 2015 17 44 48](https://cloud.githubusercontent.com/assets/2108707/9768502/0459d054-571c-11e5-9f60-12307b9bf840.png)

Question: Is there any dependency on order on which view (or edge) is being called (or used)?

**Comment by danie11am** [comment]
I'm guessing it's because offset is applied in opposite direction. Try -30 instead of 30 in the 2nd call?

**Comment by smileyborg** [comment]
@hisavali What @danie11am said is correct: the offset is relative. It's the difference between:
"The red view's left edge is 30 points from the blue view's right edge"
and
"The blue view's right edge is 30 points from the red view's left edge"
If you look at the photos above and those descriptions it should make sense.

Related: I generally recommend working left-to-right and top-to-bottom when connecting views like this, that way you always will have positive offsets.
