### ISSUE TITLE
How to  set identifier to constraint more convenient

### ISSUE THREAD

**Issue by MickeyHub** [PureLayout/PureLayout#93]
for no api of purelayout to set identifier now, I need use variable to receive the return value of purelayout api, and write code to set identifier, Does PureLayout will support more convenient api for set it?

**Comment by smileyborg** [comment]
Hi @MickeyHub, PureLayout has a few API methods to do this, please take a look at [Demo 8](https://github.com/PureLayout/PureLayout/blob/master/PureLayout/Example-iOS/Demos/iOSDemo8ViewController.swift) of the example app to see all of these being used.
