### ISSUE TITLE
Migrate to Swift2 and "UIView has no member 'autoSetPriority'", Why ? 

### ISSUE THREAD

**Issue by Luissoo** [PureLayout/PureLayout#96]
Hey,

I'm being migrating my project on Swift2.0 and i got a weird problem with PureLayout.
```
if !self.didCreateConstraints {
            
            self.imageView.autoSetDimensionsToSize(self.iconSize)
            self.imageView.autoConstrainAttribute(.Horizontal, toAttribute: .Horizontal, ofView: self, withOffset: 0.0)
            self.imageView.autoPinEdgeToSuperviewEdge(.Left)
            
            self.label.autoPinEdgesToSuperviewEdgesWithInsets(UIEdgeInsetsZero, excludingEdge: .Left)
            // 250 = UILayoutPriorityDefaultLow, symbol not found for arm64 on iOS8 SDK
            UIView.autoSetPriority(250, forConstraints: {
                let middleConstraint = self.label.autoPinEdge(.Left, toEdge: .Right, ofView: self.imageView, withOffset: self.iconToTextSpacing)
            })
            
            self.didCreateConstraints = true
        }
```

I got an error on the ```UIView.autoSetPriority``` line who is saying 
> Type 'UIView' has no member 'autoSetPriority'

I don't understand why, it worked on Xcode 6.3.

Thanks

**Comment by smileyborg** [comment]
Hi Jean-Louis,

It sounds like you've updated PureLayout to [v3.0 (release notes)](https://github.com/PureLayout/PureLayout/releases/tag/v3.0.0), which includes some breaking changes from the previous version v2.x. You should take a look at the [migration guide](https://github.com/smileyborg/PureLayout/wiki/Migrating-from-PureLayout-v2.x-to-v3.0) for more details on what you need to do.

Note that this isn't related to your change to Swift 2.0 as far as I can see, you just probably updated PureLayout at the same time.

**Comment by Luissoo** [comment]
Yes you are totally right.
I did the PureLayout V3 migration and now it's working thanks a lot !

**Comment by smileyborg** [comment]
Great! :smiley:
