### ISSUE TITLE
Type of expression is ambiguous without more context

### ISSUE THREAD

**Issue by Donwangugi** [PureLayout/PureLayout#97]
Hello,

I am getting an error when I try to use PureLayout. It is weird because I have a similiar code snippet with a different view in a different file and I get no issue. I searched on stackoverflow and saw nothing.

`self.passwordTextField.autoPinEdge(.Bottom, toEdge: .Top, ofView: self.doneButton, withOffset: -30)`

Thank you in advanced.

**Comment by smileyborg** [comment]
I don't know what the issue is without more details...can you provide a sample file or project that reproduces it?
