### ISSUE TITLE
Will purelayout ever rewritten in swift only?

### ISSUE THREAD

**Issue by laqiguy** [PureLayout/PureLayout#98]
I really love this tool, but i want to use it in swift project and don't want to make an interaction with obj-c runtime

**Comment by smileyborg** [comment]
Hi @laqiguy,

This is doubtful. Please see [this post](https://github.com/PureLayout/PureLayout/issues/80#issuecomment-132281130) for some more details. Basically, if you are in a pure Swift environment, and for whatever reason don't want to use an Objective-C library, I would recommend exploring alternatives such as [Cartography](https://github.com/robb/Cartography).

Don't forget that unless you aren't using ANY of Apple's Foundation, UIKit, or other frameworks, you're going to always be using Objective-C from your Swift code. :smiley: There's nothing wrong with this at all; Swift is designed with interoperability as a primary goal.
